name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
    
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: write
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Restore Dependencies
        run: dotnet restore src/Input.Joystick/Input.Joystick.csproj
      
      - name: Build
        run: dotnet build src/Input.Joystick/Input.Joystick.csproj -c Release --no-restore
        
 